apps/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('personal/', views.Personal.as_view(), name='personal'),
    path('news_list/', views.news_list, name='news_list'),
    path('about_me/', views.about_web, name='about_web'),
    path('contact_me/', views.contact, name='contact'),
]

apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('category_manage/', views.category_manage, name='category_manage'),
    path('add_category/', views.add_category, name='add_category'),
    path('edit_category/', views.edit_category, name='edit_category'),
    path('del_category/', views.del_category, name='del_category'),

    path('write_news/', views.WriteNews.as_view(), name='write_news'),
    path('news_manage/', views.CmsNewsManage.as_view(), name='news_manage'),
    path('edit_news/', views.EditNews.as_view(), name='edit_news'),
    path('del_news/', views.del_news, name='del_news'),

    path('staff_manage/', views.StaffManage.as_view(), name='staff_manage'),
    path('del_permission/', views.del_permission, name='del_permission'),
    path('del_staff/', views.del_staff, name='del_staff'),

    path('comment_manage', views.CommentManage.as_view(), name='comment_manage'),
    path('del_comment/', views.del_comment, name='del_comment')
]

apps/news/urls.py
from django.urls import path
from . import views


app_name = 'news'

urlpatterns = [
    path('news_detail/<int:news_id>', views.news_detail, name='news_detail'),
    path('news_comment/', views.news_comment, name='news_comment'),
    path('news_list/', views.news_list, name='news_list'),
    path('news_category/<int:category_id>', views.news_category, name='news_category'),
    path('archives/<int:year>/<int:month>', views.archives, name='archives'),
    path('up/', views.up, name='up'),
    path('down/', views.down, name='down'),

]

django_web/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.blog import views

urlpatterns = [
    path('', views.index),
    path('blog/', include('apps.blog.urls')),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cms/models.py
from django.db import models

# Create your models here.

apps/news/models.py
from django.db import models
from apps.blog.models import User


# 文章分类模型
class Category(models.Model):
    name = models.CharField(max_length=10)


# 文章模型
class News(models.Model):
    title = models.CharField(max_length=100)  # 标题
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)  # 作者
    intro = models.CharField(max_length=250)  # 文章简述
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, default='个人博客')
    pub_time = models.DateTimeField(auto_now_add=True)  # 创建时间
    content = models.TextField()  # 文章内容
    up_num = models.IntegerField(default=0, blank=True, null=True)  # 文章点赞数
    views = models.PositiveIntegerField(default=0)  # 文章浏览数

    class Meta:
        ordering = ['-pub_time']

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])


# 评论模型
class Comment(models.Model):
    comment_content = models.TextField(max_length=150)  # 评论内容
    pub_time = models.DateTimeField(auto_now_add=True)  # 评论创建时间
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE)  # 评论作者
    comment_news = models.ForeignKey(News, on_delete=models.CASCADE, related_name='comments')  # 给哪个文章写的评论
    origin_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True)  # 2级评论，可以为空

    class Meta:
        ordering = ['-pub_time']


# 点赞记录模型
class UpAndDown(models.Model):

    up_user = models.ForeignKey(User, related_name='up_user', on_delete=models.CASCADE)  # 点赞人
    up_news = models.ForeignKey(News, related_name='up_news', on_delete=models.CASCADE)  # 点赞的文章
    up = models.BooleanField(default=0)  # 记录是否对这个文章有过点赞

apps/cms/forms.py
from django import forms
from apps.forms import FormMixin


class WriteNewsForms(forms.Form, FormMixin):
    title = forms.CharField(max_length=100, error_messages={
        'max_length': '标题太长了！',
        'required': '标题不要忘了写！'
    })
    category = forms.IntegerField(error_messages={
        'required': '分类不要忘了写！'
    })
    intro = forms.CharField(max_length=250, error_messages={
        'max_length': '摘要太长了！',
        'required': '不要忘了写摘要！'
    })
    content = forms.CharField(error_messages={
        'required': '不要忘了写文章内容！'
    })


class EditNewsForm(forms.Form, FormMixin):
    id = forms.IntegerField()
    title = forms.CharField(max_length=100, error_messages={
        'max_length': '标题太长了！',
        'required': '标题不要忘了写！'
    })
    category = forms.IntegerField(error_messages={
        'required': '分类不要忘了写！'
    })
    intro = forms.CharField(max_length=200, error_messages={
        'max_length': '摘要太长了！',
        'required': '不要忘了写摘要！'
    })
    content = forms.CharField(error_messages={
        'required': '不要忘了写文章内容！'
    })

apps/cms/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Group
from django.core.paginator import Paginator
from django.db.models import Count, F
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from apps.blog.decorator import blog_super_decorator
from apps.blog.models import User
from apps.news.models import Category, News, Comment
from django.views.decorators.http import require_POST, require_GET
from utils import restful
from apps.cms.forms import WriteNewsForms, EditNewsForm
from django.http import Http404
from datetime import datetime
from django.utils.timezone import make_aware
from django.contrib.admin.views.decorators import staff_member_required


@staff_member_required(login_url='index')
def index(request):
    return render(request, 'cms/index.html')


@require_GET
@permission_required(perm='news.view_category', login_url='/')
def category_manage(request):
    categories = Category.objects.annotate(news_count=Count('news'))
    return render(request, 'cms/category.html', context={'categories': categories})


@require_POST
@permission_required(perm='news.add_category', login_url='/')
def add_category(request):
    try:
        name = request.POST.get('name')
        if not Category.objects.filter(name=name).exists():
            Category.objects.create(name=name)
            return restful.ok()
        else:
            return restful.params_error(message='分类已存在')
    except Exception:
        pass


@require_POST
@permission_required(perm='news.change_category', login_url='/')
def edit_category(request):
    try:
        pk = request.POST.get('pk')
        name = request.POST.get('name')
        old_category = Category.objects.filter(pk=pk)
        if not Category.objects.filter(name=name).exists():
            old_category.update(name=name)
            return restful.ok()
        else:
            return restful.params_error(message='分类已存在')
    except Exception:
        pass


@require_POST
@permission_required(perm='news.delete_category', login_url='/')
def del_category(request):
    try:
        pk = request.POST.get('pk')
        category = Category.objects.filter(pk=pk)
        if category.exists():
            category.delete()
            return restful.ok()
        else:
            return restful.params_error(message='分类不存在！')
    except Exception:
        pass


@method_decorator(permission_required(perm='news.add_news', login_url='/'), name='dispatch')
class WriteNews(View):

    def get(self, request):
        categories = Category.objects.all()
        return render(request, 'cms/write_news.html', context={'categories': categories})

    def post(self, request):
        form = WriteNewsForms(request.POST)
        if form.is_valid():
            user = request.user
            title = form.cleaned_data.get('title')
            category_id = form.cleaned_data.get('category')
            category = Category.objects.filter(pk=category_id).first()
            intro = form.cleaned_data.get('intro')
            content = form.cleaned_data.get('content')
            News.objects.create(title=title, category=category, intro=intro, content=content, author=user)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


@method_decorator(permission_required(perm='news.view_news', login_url='/'), name='dispatch')
class CmsNewsManage(View):

    def get(self, request):
        page = int(request.GET.get('p', 1))  # 获取当前的页码, 如果没有拿到，默认第一页，保险起见，转化为整数。
        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        category_id = int(request.GET.get('category') or 0)  # 获取分类的id, 如果没有就默认为1

        # 使用select_related提前将相关联的数据提取出来，避免模板中在一次查询
        newses = News.objects.select_related('category', 'author')

        if start or end:
            if start:
                # 将字符串时间改为格式化的时间
                start = datetime.strptime(start, '%Y/%m/%d')
            else:
                # 如果没有设置开始查询时间，则默认使用2019/01/01
                start = datetime(year=2019, month=1, day=1)
            if end:
                end = datetime.strptime(end, '%Y/%m/%d')
            else:
                end = datetime.today()

            newses = newses.filter(pub_time__range=(make_aware(start), make_aware(end)))
            # newses = newses.filter(pub_time__range=(start, end))

        if title:
            newses = newses.filter(title__icontains=title)

        if category_id:
            newses = newses.filter(category=category_id)

        paginator = Paginator(newses, 5)  # 要实现分页的模型的对象是newses， 每页5条数据。
        page_obj = paginator.page(page)  # 获取当前页的对象

        context = {
            # object_list 方法是将当前页的所有对象放入列表中，方便前端遍历
            'page_objs': page_obj.object_list,  # 这个地方不能再传newses了，因为要显示分页后的数据
            'categories': Category.objects.all(),
            'title': title,
            'category_id': category_id,
            'paginator': paginator,
            'current_page': page_obj.number,
            'num_pages': paginator.num_pages,
            'page_obj': page_obj,  # 后面4项一定要传，如果没有传，在模板中调用这三个方法是不行的。
        }
        return render(request, 'cms/news_manage.html', context=context)


@method_decorator(permission_required(perm='news.change_news', login_url='/'), name='dispatch')
class EditNews(View):

    def get(self, request):
        try:
            news_id = request.GET.get('news_id')
            news = News.objects.get(pk=news_id)
            return render(request, 'cms/write_news.html', context={'news': news, 'categories': Category.objects.all()})
        except Exception:
            raise Http404

    def post(self, request):
        form = EditNewsForm(request.POST)
        if form.is_valid():
            id = form.cleaned_data.get('id')
            title = form.cleaned_data.get('title')
            category = form.cleaned_data.get('category')
            intro = form.cleaned_data.get('intro')
            content = form.cleaned_data.get('content')
            News.objects.filter(pk=id).update(title=title, category=category, intro=intro, content=content)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


@require_POST
@permission_required(perm='news.delete_news', login_url='/')
def del_news(request):
    try:
        pk = request.POST.get('pk')
        News.objects.filter(pk=pk).delete()
        return restful.ok()
    except Exception:
        return restful.params_error(message='要删除的新闻不存在！')


@method_decorator(blog_super_decorator, name='dispatch')
class StaffManage(View):

    def get(self, request):
        staffs = User.objects.filter(is_staff=True).prefetch_related('groups')
        groups = Group.objects.all()
        return render(request, 'cms/staffs.html', context={
            'staffs': staffs,
            'groups': groups
        })

    def post(self, request):
        telephone = request.POST.get('telephone')
        group_id = request.POST.get('group')
        user = User.objects.filter(telephone=telephone).first()
        if user:
            user.is_staff = True
            group = Group.objects.filter(pk=group_id).first()
            user.groups.add(group)
            user.save()
            return restful.ok()
        else:
            return restful.params_error(message='这个员工好像不存在呀！')


@require_POST
@blog_super_decorator
def del_permission(request):
    try:
        telephone = request.POST.get('telephone')
    except Exception:
        return restful.params_error(message='这个员工好像不存在呀')
    user = User.objects.filter(telephone=telephone).first()
    user.groups.clear()
    user.save()
    return restful.ok()


@require_POST
@blog_super_decorator
def del_staff(request):
    try:
        telephone = request.POST.get('telephone')
    except Exception:
        return restful.params_error(message='这个员工好像不存在呀')
    User.objects.filter(telephone=telephone).first().delete()

    return restful.ok()


@method_decorator(blog_super_decorator, name='dispatch')
class CommentManage(View):

    def get(self, request):
        page = int(request.GET.get('p', 1))  # 获取当前的页码, 如果没有拿到，默认第一页，保险起见，转化为整数。
        commnets = Comment.objects.select_related('comment_author', 'comment_news').all()
        paginator = Paginator(commnets, 10)  # 要实现分页的模型的对象是newses， 每页10条数据。
        page_obj = paginator.page(page)  # 获取当前页的对象

        context = {
            # object_list 方法是将当前页的所有对象放入列表中，方便前端遍历
            'page_objs': page_obj.object_list,  # 这个地方不能再传commnets了，因为要显示分页后的数据
            'paginator': paginator,
            'current_page': page_obj.number,
            'num_pages': paginator.num_pages,
            'page_obj': page_obj,  # 后面4项一定要传，如果没有传，在模板中调用这三个方法是不行的。
        }
        return render(request, 'cms/comment_manage.html', context=context)


@require_POST
@blog_super_decorator
def del_comment(request):
    try:
        pk = request.POST.get('pk')
        Comment.objects.filter(pk=pk).first().delete()
        return restful.ok()
    except Exception:
        return restful.params_error(message='这个评论好像不存在')

front/templates/cms/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bokebook | CMS后台管理中心</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
    <script src="{% static 'js/alert.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>

    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    {% block head %}

    {% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <!-- 下面是CMS页面顶部代码 -->
    <header class="main-header">
        <!-- Logo -->
        <a href="" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>CMS</b>后台发布中心</span>
        </a>
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only"></span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">

                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{% static "images/333.png" %}"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">{{ request.user.username }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="{% static "images/333.png" %}"
                                     class="img-circle" alt="User Image">

                                <p>
                                    <small>这里面装着介绍</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{% url 'blog:personal' %}" class="btn btn-default btn-flat"
                                       target="_blank">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'blog:logout' %}" class="btn btn-default btn-flat">退出</a>
                                </div>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
        </nav>
    </header>
    <!-- CMS页面左侧可隐藏代码 -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar" style="height: auto;">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{% static "images/333.png" %}"
                         class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>{{ request.user.username }}</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>

        </section>
        <ul class="sidebar-menu" data-widget="tree">
            <li>
                <a href="{% url 'cms:index' %}"><i class="fa fa-home"></i><span>首页</span></a>
            </li>

            {# 下面对权限进行限定，如果有权限则可以看到并能操作，这个perms是settings中的auth上下文处理器返回的 #}
            {% if perms.news.change_news %}
                <li>
                    <a href="{% url 'cms:write_news' %}"><i class="fa fa-pencil-square-o"></i><span>发布新闻</span></a>
                </li>
                <li>
                    <a href="{% url 'cms:category_manage' %}"><i class="fa fa-tag"></i><span>新闻分类</span></a>
                </li>
                <li>
                    <a href="{% url 'cms:news_manage' %}"><i class="fa fa-list"></i><span>新闻管理</span></a>
                </li>
                <li>
                    <a href="{% url 'cms:comment_manage' %}"><i class="fa fa-list"></i><span>评论管理</span></a>
                </li>
            {% endif %}
            {#            {% if perms.news.delete_comment %}#}
            {# 管理评论功能还为实现 留空待实现#}
            {#            {% endif %}#}

            <li>
                <a href="{% url 'cms:staff_manage' %}"><i class="fa fa-list"></i><span>员工管理</span></a>
            </li>
            <li>
                <a href="{% url 'blog:index' %}" target="_blank"><i class="fa fa-home"></i><span>返回博客首页</span></a>
            </li>
        </ul>
    </aside>
    <!-- CMS主题部分代码 -->
    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}

            {% endblock %}
        </section>
        <section class="content">
            {% block content %}{% endblock %}
        </section>
    </div>
    <!-- CMS主题部分底部代码-->
    <footer class="main-footer">
        <span>欢迎来到CMS后台发布中心</span>
    </footer>
</div>
</body>
</html>

front/templates/cms/category.html
{% extends 'cms/base.html' %}

{% block head %}
    <script src="{% static 'js/addcategory.js' %}"></script>
{% endblock %}
{% block content-header %}
    <h1>新闻分类</h1>
{% endblock %}

{% block content %}


    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button class="btn btn-primary" id="add-btn">添加分类</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>新闻分类</th>
                            <th>新闻数量</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in categories %}
                            <tr data-pk="{{ category.id }}" data-name="{{ category.name }}">
                                <td>{{ category.name }}</td>
                                <td>{{ category.news_count }}</td>
                                <td>
                                    <button class="btn btn-danger delete-btn btn-xs">删除</button>
                                    <button class="btn btn-primary edit-btn btn-xs">编辑</button>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/index.html
{% extends 'cms/base.html' %}


{% block content-header %}
    <span>每天都需要一个微笑</span>
{% endblock %}


{% block content %}
  <div class="row">
    <div class="col-md-12">

        <span>这是cms首页</span>
    </div>
  </div>
{% endblock %}

front/templates/cms/news_manage.html
{% extends 'cms/base.html' %}

{% block head %}
    <link rel="stylesheet"
          href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'js/news_manage.js' %}"></script>
{#    <script src="{% static 'js/newsmanage.min.js' %}"></script>#}

{% endblock %}

{% block content-header %}
    <h1>新闻管理</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <form action="" class="form-inline">
                        {#                    form表单默认的method是GET方法，这里就是使用GET方法，所以就不写了#}
                        <div class="form-group">
                            <label>时间：</label>
                            <input type="text" class="form-control" placeholder="开始时间" id="starttime" name="start"
                                   data-date-end-date="0d"
                                   readonly>
                            <span>==></span>
                            <input type="text" class="form-control" placeholder="结束时间" id="endtime" name="end"
                                   readonly data-date-end-date="0d">
                        </div>
                        <div class="form-group" style="margin-left: 40px">
                            <label for="key-word">关键字查找:</label>
                            {% if title %}
                                <input type="text" class="form-control" id="key-word" placeholder="篮球" name="title"
                                       value="{{ title }}">
                            {% else %}
                                <input type="text" class="form-control" id="key-word" placeholder="篮球" name="title">
                            {% endif %}
                        </div>
                        <div class="form-group dropdown" style="margin-left: 40px">
                            <label for="category-input">按分类查找：</label>
                            <select name="category" id="category-input" class="form-control">
                                {% if category_id == 0 %}
                                    <option value="0" selected>全部分类</option>
                                {% else %}
                                    <option value="0">全部分类</option>
                                {% endif %}
                                {% for category in categories %}
                                    {% if category.id == category_id %}
                                        <option value="{{ category.id }}" selected>{{ category.name }}</option>
                                    {% else %}
                                        <option value="{{ category.id }}">{{ category.name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group" style="margin-left: 50px">
                            <button class="btn btn-primary">查询</button>
                        </div>
                        <div class="form-group ">
                            <a href="{% url 'cms:news_manage' %}" class="btn btn-warning">清除查询</a>
                        </div>
                    </form>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th class="col-md-5">新闻标题</th>
                            <th class="col-md-1">新闻分类</th>
                            <th class="col-md-2">发布时间</th>
                            <th class="col-md-2">发布人</th>
                            <th class="col-md-2">操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for page_obj in page_objs %}
                            <tr>
                                <td><a target="_blank"
                                       href="{% url 'news:news_detail' news_id=page_obj.id %}">{{ page_obj.title }}</a>
                                </td>
                                <td>{{ page_obj.category.name }}</td>
                                <td>{{ page_obj.pub_time }}</td>
                                <td>{{ page_obj.author.username }}</td>
                                <td>
                                    {% if user.is_superuser %}
                                    <button class="btn btn-danger delete-btn btn-xs" data-news-id="{{ page_obj.id }}">删除
                                    </button>
                                    <a href="{% url 'cms:edit_news' %}?news_id={{ page_obj.id }}"
                                       class="btn btn-primary btn-xs">编辑</a>
                                    {% else %}
                                        <span class="btn btn-primary btn-xs">删除</span>
                                        <span class="btn btn-primary btn-xs">编辑</span>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="footer">
                    <ul class="pagination pull-right">
                            {% if page_obj.has_previous %}
                                <li>
                                <a href="?p={{ page_obj.previous_page_number }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                                </li>
                            {% else %}
                                <li class="disabled">
                                <a href="javascript:void(0);" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                </a>
                                </li>
                            {% endif %}
                        <li class="disabled">
                            <span class="current">
                            第{{ current_page }}/{{ num_pages }}页
                        </span>
                        </li>

                            {% if page_obj.has_next %}
                                <li class="next">
                                <a href="?p={{ page_obj.next_page_number }}"
                                   aria-label="Next">&raquo;</a>
                                </li>
                            {% else %}
                                <li class="disabled">
                                <a href="javascript:void(0);" aria-label="Next">&raquo;</a>
                                </li>
                            {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}