apps/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('personal/', views.Personal.as_view(), name='personal'),
    path('news_list/', views.news_list, name='news_list'),
    path('about_me/', views.about_web, name='about_web'),
    path('contact_me/', views.contact, name='contact'),
]

apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('category_manage/', views.category_manage, name='category_manage'),
    path('add_category/', views.add_category, name='add_category'),
    path('edit_category/', views.edit_category, name='edit_category'),
    path('del_category/', views.del_category, name='del_category'),

    path('write_news/', views.WriteNews.as_view(), name='write_news'),
    path('news_manage/', views.CmsNewsManage.as_view(), name='news_manage'),
    path('edit_news/', views.EditNews.as_view(), name='edit_news'),
    path('del_news/', views.del_news, name='del_news'),

    path('staff_manage/', views.StaffManage.as_view(), name='staff_manage'),
    path('del_permission/', views.del_permission, name='del_permission'),
    path('del_staff/', views.del_staff, name='del_staff'),

    path('comment_manage', views.CommentManage.as_view(), name='comment_manage'),
    path('del_comment/', views.del_comment, name='del_comment')
]

apps/news/urls.py
from django.urls import path
from . import views


app_name = 'news'

urlpatterns = [
    path('news_detail/<int:news_id>', views.news_detail, name='news_detail'),
    path('news_comment/', views.news_comment, name='news_comment'),
    path('news_list/', views.news_list, name='news_list'),
    path('news_category/<int:category_id>', views.news_category, name='news_category'),
    path('archives/<int:year>/<int:month>', views.archives, name='archives'),
    path('up/', views.up, name='up'),
    path('down/', views.down, name='down'),

]

django_web/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.blog import views

urlpatterns = [
    path('', views.index),
    path('blog/', include('apps.blog.urls')),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.contrib.auth.models import PermissionsMixin, BaseUserManager
from django.core import validators
from shortuuidfield import ShortUUIDField


class UserManager(BaseUserManager):

    def _create_user(self, telephone, username, password, **kwargs):

        if not telephone:
            return ValueError('手机号码好像忘了！')
        if not username:
            return ValueError('请给自己取一个牛逼的名字吧！')
        if not password:
            return ValueError('没有密码，怎么登录呀！')
        user = self.model(telephone=telephone, username=username, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, telephone, username, password, **kwargs):
        kwargs['is_superuser'] = False
        return self._create_user(telephone=telephone, username=username, password=password, **kwargs)

    def create_superuser(self, telephone, username, password, **kwargs):
        kwargs['is_staff'] = True
        kwargs['is_superuser'] = True
        return self._create_user(telephone=telephone, username=username, password=password, **kwargs)



class User(AbstractBaseUser, PermissionsMixin):
    uuid = ShortUUIDField(primary_key=True)
    username = models.CharField(max_length=15)
    telephone = models.CharField(max_length=11, unique=True, validators=[validators.RegexValidator(r'1[35678]\d{9}')])
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'telephone'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

apps/blog/forms.py
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError

from apps.forms import FormMixin


class LoginForm(forms.Form, FormMixin):
    telephone = forms.CharField(
        max_length=11,
        min_length=11,
        strip=True,
        error_messages={
            'max_length': '请正确输入手机号码！',
            'min_length': '请输入11位手机号码！',
            'required': "手机号不能为空!"
        })
    password = forms.CharField(
        max_length=16,
        min_length=8,
        strip=True,
        error_messages={
            'max_length': '密码输入错误！',
            'min_length': '密码输入错误！',
            'required': "密码不能为空!"
        })
    remember = forms.IntegerField(required=False)


class RegisterForm(forms.Form, FormMixin):
    telephone = forms.CharField(
        validators=[validators.RegexValidator(r'1[35678]\d{9}', '请输入正确的手机号码!')],
        max_length=11,
        min_length=11,
        strip=True,
        error_messages={
            'max_length': '请正确输入手机号码！',
            'min_length': '请输入11位手机号码！',
            'required': "手机号不能为空！"
        })
    username = forms.CharField(
        max_length=50,
        strip=True,
        error_messages={
            'required': "用户名不能为空！"
        })
    password1 = forms.CharField(
        max_length=16,
        min_length=8,
        strip=True,
        error_messages={
            'max_length': '密码长度太长！',
            'min_length': '密码不足8位！',
            'required': "密码不能为空！"
        })
    password2 = forms.CharField(
        max_length=16,
        min_length=8,
        strip=True,
        error_messages={
            'max_length': '密码长度太长！',
            'min_length': '密码不足8位！',
            'required': "密码不能为空！"
        })

    def clean_username(self):
        # 从cleaned_data中取出想要的数据
        username = self.cleaned_data.get("username")
        values=['sb', 'SB', '傻逼', '傻狗', '全家死了', '作者是傻逼', '垃圾']
        for value in values:
            if value in username:
                # 错误就抛异常
                raise ValidationError("不要使用侮辱性的用户名！")
            else:
                return username


class EditForm(forms.Form, FormMixin):
    telephone = forms.CharField(
        max_length=11,
        min_length=11,
        strip=True,
        error_messages={
            'max_length': '请正确输入手机号码！',
            'min_length': '请输入11位手机号码！',
            'required': "手机号不能为空!"
        })

    old_pwd = forms.CharField(
        max_length=16,
        min_length=8,
        strip=True,
        error_messages={
            'max_length': '密码输入错误！',
            'min_length': '密码输入错误！',
            'required': "密码不能为空!"
        })
    new_pwd1 = forms.CharField(
        max_length=16,
        min_length=8,
        strip=True,
        error_messages={
            'max_length': '密码输入错误！',
            'min_length': '密码输入错误！',
            'required': "密码不能为空!"
        })
    new_pwd2 = forms.CharField(
        max_length=16,
        min_length=8,
        strip=True,
        error_messages={
            'max_length': '密码输入错误！',
            'min_length': '密码输入错误！',
            'required': "密码不能为空!"
        })

apps/blog/views.py
from django.conf import settings
from django.db.models import Count
from django.shortcuts import render, redirect
from django.urls import reverse
from apps.news.serializers import NewsListSerializer
from utils import restful
from django.views import View
from .models import User
from apps.news.models import News, Category
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm, LoginForm, EditForm


def index(request):
    count = settings.ONE_PAGE_NEWS_COUNT
    newses = News.objects.annotate(news_num=Count('pub_time__month'), comments_num=Count('comments')).all()[0:count]
    categories = Category.objects.annotate(news_count=Count('news'))
    hot_newses = News.objects.order_by('-views')[0:5]
    archives = News.objects.dates('pub_time', 'month', order='DESC').annotate(news_num=Count('id'))
    return render(request, 'blog/index.html', context={
        "newses": newses,
        'categories': categories,
        'hot_newses': hot_newses,
        'archives': archives
    })


def news_list(request):
    page = int(request.GET.get('p', 1))
    start = int((page - 1) * settings.ONE_PAGE_NEWS_COUNT)
    end = int(start + settings.ONE_PAGE_NEWS_COUNT)
    newses = News.objects.select_related('category', 'author').annotate(comments_num=Count('comments')).all()[start:end]
    serializer = NewsListSerializer(newses, many=True)
    return restful.result(data=serializer.data)


def logout_view(request):
    logout(request)
    return redirect(reverse('blog:index'))


class LoginView(View):

    def get(self):
        return redirect(reverse('blog:index'))

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            telephone = form.cleaned_data.get('telephone')
            password = form.cleaned_data.get('password')
            remember = form.cleaned_data.get('remember')
            user = authenticate(request, username=telephone, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    if remember:
                        request.session.set_expiry(None)
                    else:
                        request.session.set_expiry(0)
                    return restful.ok()
                else:
                    return restful.params_error(message='此账号被关进了小黑屋')
            else:
                if User.objects.filter(telephone=telephone).exists():
                    return restful.params_error(message='密码错误！')
                else:
                    return restful.params_error(message='还未进行注册，请进行注册！')
        else:
            return restful.params_error(message=form.get_errors())


class RegisterView(View):

    def get(self):
        return redirect(reverse('blog:index'))

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            telephone = form.cleaned_data.get('telephone')
            username = form.cleaned_data.get('username')
            password1 = form.cleaned_data.get('password1')
            password2 = form.cleaned_data.get('password2')
            exists = User.objects.filter(telephone=telephone).exists()
            if not exists:
                if password1 == password2:
                    user = User.objects.create_user(telephone=telephone, username=username, password=password1)
                    login(request, user)
                    return restful.ok()
                else:
                    message = '两次输入密码不一致，请重新输入！'
                    return restful.params_error(message=message)
            else:
                message = '你的手机号码已被注册了！'
                return restful.params_error(message=message)
        else:
            return restful.params_error(message=form.get_errors())


class Personal(View):

    def get(self, request):
        user = request.user
        personal_newses = News.objects.select_related('category').filter(author=user)

        return render(request, 'blog/personal.html', context={
            "personal_newses": personal_newses
        })

    def post(self, request):
        form = EditForm(request.POST)
        if form.is_valid():
            telephone = form.cleaned_data.get('telephone')
            old_pwd = form.cleaned_data.get('old_pwd')
            new_pwd1 = form.cleaned_data.get('new_pwd1')
            new_pwd2 = form.cleaned_data.get('new_pwd2')
            if telephone == str(request.user):
                if old_pwd != new_pwd1:
                    if new_pwd1 == new_pwd2:
                        user = authenticate(request, username=telephone, password=old_pwd)
                        if user:
                            user = User.objects.filter(telephone=telephone).first()
                            user.set_password(new_pwd2)
                            user.save()
                            login(request, user)
                            return restful.ok()
                        else:
                            return restful.params_error(message='输入的旧密码错误')
                    else:
                        return restful.params_error(message='两次输入的新密码不一致！')
                else:
                    return restful.params_error(message='新旧密码一样！重新输入新密码！')
            else:
                return restful.params_error(message='请不要耍小聪明，输入自己的手机号码！')

        else:
            return restful.params_error(message=form.get_errors())


def about_web(request):
    return render(request, 'blog/about_web.html')


def contact(request):
    return render(request, 'blog/contact_me.html')

front/templates/blog/about_web.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>关于网站</title>
</head>
<body>
    <div style="margin-top: 10%;margin-left: 10%">
        <h4>
            关于这个网站
        </h4>
        <p>
            用来记录学习过程中遇到的一些问题，并不是纯粹的技术网站，还会分享一些热点新闻什么的。
        </p>
        <p>技术博客：https://blog.csdn.net/weixin_43972292</p>
    </div>
</body>
</html>

front/templates/blog/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>BookBoKe</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/body.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">

    {#    <link rel="shortcut icon" href="#"/>#}

    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->

    {% block static %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand">BookBoKe</span>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">首页</a></li>
                {% for category in categories %}
                    <li><a href="/news/news_category/{{ category.id }}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            <span data-toggle="modal">你好，{{ user.username }}<span class="caret"></span></span>
                        </a>
                        <ul class="dropdown-menu">
                            {% if user.is_staff %}
                                <li><a href="{% url 'cms:index' %}">CMS管理中心</a></li>
                                <li><a href="{% url 'blog:personal' %}">个人信息管理</a></li>
                                <li role="separator" class="divider"></li>
                            {% endif %}
                            <li>
                                <a href="{% url 'blog:logout' %}">
                                    <span data-toggle="modal">退出登录</span>
                                </a>
                            </li>
                            <li>
                                <a>
                                    <span data-toggle="modal" id="edit-btn">修改密码</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a>
                            <span data-toggle="modal" id="login-btn">登录</span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <span data-toggle="modal" id="register-btn">注册</span>
                        </a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>
<div class="container" style="min-height: 100%;">
    <div class="row" style="width: 100%;height: 51px">

    </div>
    <div class="row">
        <div class="container col-xs-9">
            {% block content %}

            {% endblock %}
        </div>
        <div class="col-xs-1"></div>
        <div class="container col-xs-2">
            {% block sidebar %}

            {% endblock %}
        </div>
    </div>

</div>
<div class="container" style="position: relative;bottom: 0;left:0;right:0;margin-bottom: 20px;width: 100%">
    <div>
        <div class="row col-xs-11">
            <div class="footer" style="margin-top: 20px;float: right">
                <span style="margin-right: 10px">
                    <a href="{% url 'blog:about_web' %}">关于网站</a>
                </span>
                <span>
                    <a href="{% url 'blog:contact' %}">联系我们</a>
                </span>
            </div>
        </div>
    </div>
</div>

<div class="chapter ">
    <a href="#top">
        <button class="back_to_top" style=""><span class="glyphicon glyphicon-triangle-top">Top</span></button>
    </a>
</div>


<div class="modal" id="login-box" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="login-modal">
                <form action="" method="post" class="login-form">
                    {% csrf_token %}
                    <span class="login-close-btn glyphicon glyphicon-remove"></span>
                    <p class="title">登 录</p>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="手机号码" id="login-telephone">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="密码" id="login-pwd">
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="remember" value="1"> 记住我
                        </label>
                    </div>
                    <input class="input-btn" type="reset" value="重新填写">
                    <input type="submit" class="login-btn" value="点我登录">
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal" id="register-box" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="register-box">
                <form action="" method="post" class="register-form">
                    {% csrf_token %}
                    <span class="register-close-btn glyphicon glyphicon-remove"></span>
                    <p class="title">请注册</p>
                    <div class="form-group">
                        <input id='register-telephone' type="text" class="form-control" placeholder="手机号"
                               name="telephone">
                    </div>
                    <div class="form-group">
                        <input id='register-username' type="text" class="form-control" placeholder="用户名"
                               name="username">
                    </div>
                    <div class="form-group">
                        <input id='register-pwd1' type="password" class="form-control" placeholder="密码"
                               name="password1">
                    </div>
                    <div class="form-group">
                        <input id='register-pwd2' type="password" class="form-control" placeholder="确认密码"
                               name="password2">
                    </div>
                    <input class="reset-btn" type="reset" value="重新填写">
                    <input type="submit" class="register-btn" value="点击注册">
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal" id="edit-box" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="edit-box">
                <form action="" method="post" class="edit-form">
                    {% csrf_token %}
                    <span class="edit-close-btn glyphicon glyphicon-remove"></span>
                    <p class="title">修改密码</p>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="手机号码" id="edit-telephone">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="输入旧密码" id="old-pwd">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="输入新密码" id="new-pwd1">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="确认新密码" id="new-pwd2">
                    </div>

                    <input class="input-btn" type="reset" value="重新填写" style="float: left">
                    <input type="submit" class="edit-btn" value="点我修改" style="float: right">
                </form>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
<script src="{% static 'js/ajax.js' %}"></script>
<script src="{% static 'js/register.js' %}"></script>
<script src="{% static 'js/index.js' %}"></script>
<script src="{% static 'js/news_category.js' %}"></script>
<script src="{% static 'arttemplate/template-web.js' %}"></script>
<script src="{% static 'js/comment.js' %}"></script>
<script src="{% static 'js/updown.js' %}"></script>
<script src="{% static 'js/message.js' %}"></script>
<script type="text/javascript">
    $(function () {
        let top = $('<a id="top"></a>');
        top.click(function () {
            top.prependTo('body');
        });
    });
</script>
</body>
</html>

front/templates/blog/contact_me.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>联系我们</title>
</head>
<body>
    <div style="margin-top: 10%;margin-left: 10%">
        <p>这里面什么都没有，赶紧给我留言吧！</p>
    </div>
</body>
</html>

front/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block static %}
    <script id="news-list" type="text/html">
        {% verbatim %}
        {{ each newses news index }}
        <li class="news-body">
            <div class="col-xs-12">
                <div>
                    <h4 class="article-title">{{ news.title }}</h4>
                </div>
                <div class="user-time-box">
                    <span class="time-box">{{ news.pub_time|dateFormat }}</span>
                    <span style="margin-left:10px;">阅读数 {{ news.views }}</span>
                </div>
                <div class="article-desc">
                    {{ news.intro }}...
                </div>
                <div class="up-down-box">
                    <div class="up">
                        <span class="glyphicon glyphicon-star">{{ news.up_num }}</span>
                    </div>

                    <div class="intro-box">
                        <a href="/news/news_detail/{{ news.id }}">阅读更多</a>
                    </div>
                </div>
            </div>
        </li>
        {{ /each }}
        {% endverbatim %}
    </script>

{% endblock %}


{% block content %}
    <div class="news-box">
        <ul class="news-list-group">
            {% for news in newses %}
                <li class="news-body">
                    <div class="col-xs-12">
                        <div>
                            <h4 class="article-title">{{ news.title }}</h4>
                        </div>
                        <div class="user-time-box">
                            <span class="time-box">{{ news.pub_time }}</span>
                            <span style="margin-left:10px;">阅读数 {{ news.views }}</span>
                        </div>
                        <div>
                        </div>
                        <div class="article-desc">
                            {{ news.intro }}...
                        </div>
                        <div class="up-down-box">
                            <div class="up">
                                <span class="glyphicon glyphicon-star">{{ news.up_num }}</span>
                            </div>
                            <div class="intro-box">
                                <a href="{% url 'news:news_detail' news.id %}">阅读更多</a>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}

        </ul>

    </div>
    <div class="load-more-group">
        <button class="load-more" id="load-more-btn">
            查看更多
        </button>
    </div>
{% endblock %}
{% block sidebar %}
    {% include 'blog/sidebar.html' %}
{% endblock %}

front/templates/blog/personal.html
{% extends 'blog/base.html' %}


{% block content %}
    <div class="container" style="margin-top: 50px">
        <h3>
            我发布的文章:
        </h3>
        <div class="row col-xs-12">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th class="col-xs-4">文章标题</th>
                    <th class="col-xs-2">文章分类</th>
                    <th class="col-xs-2">发布时间</th>
                    <th class="col-xs-2">获得的赞数</th>
                    <th class="col-xs-2">阅读数</th>
                </tr>
                </thead>
                <tbody>
                {% for personal_news in personal_newses %}
                    <tr>
                        <td>{{ personal_news.title }}</td>
                        <td>{{ personal_news.category.name }}</td>
                        <td>{{ personal_news.pub_time }}</td>
                        <td>{{ personal_news.up_num }}</td>
                        <td>{{ personal_news.views }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

front/templates/blog/sidebar.html
<div class="sidebar-box">
    <div class="category-box">
        <div class="category-title">
            <span class="glyphicon glyphicon-tags"></span><span class="category-box1">分类：</span>
        </div>
        <div>
            {% for category in categories %}
                <p class="category-tags">
                    <a href="{% url 'news:news_category' category.id %}">{{ category.name }}({{ category.news_count }})</a>
                </p>
            {% endfor %}
        </div>
    </div>
    <div class="widget widget-archives">
        <span class="glyphicon glyphicon-th-large"></span><span class="widget-title">归档：</span>
        <ul>
            {% for date in archives %}
                <li class="date-box">
                    <a href="{% url 'news:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }}
                        月</a>
                </li>
            {% empty %}
                暂无归档！
            {% endfor %}
        </ul>
    </div>

    <div class="hot-news-box">
        <div>
            <span class="glyphicon glyphicon-fire"></span><span class="hot-news">热门文章：</span>
        </div>
        <ul>
            {% for hot_news in hot_newses %}
                <li class="li-hot-news">
                    <a href="{% url 'news:news_detail' hot_news.id %}">{{ hot_news.title }}</a>
                    <p>阅读数：{{ hot_news.views }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>